import { useEffect, useState } from 'react';
import { ArrowRight, Menu, Sparkles, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiService } from '../../../services/api';
import { SiteSettings } from '../../../types';

const fallback:SiteSettings={brandName:'suffer',brandTld:'.info',heroBadge:'A profile platform built around you',heroTitle:'Your entire online identity, in one place.',heroSubtitle:'Build a profile that actually feels like yours. Links, socials, music, effects, badges, backgrounds and more — all controlled from one easy dashboard.',primaryButton:'Create your profile',secondaryButton:'Explore the experience',accentColor:'#ef4444',secondaryColor:'#cbd5e1',backgroundColor:'#050506',panelColor:'#0d0d0f',gridOpacity:.12,glowOpacity:.2,particles:true,grid:true,ghostMode:true,featureSection:true,mediaLayers:[],siteAnimations:[],announcement:'',showcaseLabel:'Showcase',featuresLabel:'Features',signInLabel:'Sign in',createLabel:'Create page',primaryButtonUrl:'/register',secondaryButtonUrl:'#showcase',heroAlignment:'center',seoTitle:'suffer.info',seoDescription:'Create a profile that actually feels like yours.',seoImage:'',footerText:'Your page. Your links. Your rules.',effectsIntensity:1,navStyle:'glass',heroSize:'fullscreen',heroWidth:'standard',headlineFont:'Inter',headlineWeight:600,headlineSize:8,bodySize:1,pageRadius:22,sectionSpacing:28,noise:false,vignette:true,scanlines:false,animatedGradient:true,mouseGlow:true,hoverLift:true,buttonStyle:'solid',buttonRadius:16,showTrustBar:true,trustText:'Free to start · No design skills needed · Your profile, your rules.',showcaseTitle:'Make it yours',showcaseDescription:'One editor for your profile, links, music, badges, effects and media.',featuresTitle:'Everything important is one tap away.',featuresDescription:'Powerful controls without making you learn code.',featureCards:[],customCss:''};

export const HomePage:React.FC=()=>{
 const [site,setSite]=useState<SiteSettings>(fallback);
 const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{apiService.getSiteSettings().then(setSite).catch(()=>{});},[]);
 const particles=Array.from({length:24},(_,i)=>({left:(i*41)%100,top:(i*67)%80,delay:(i%8)*.35}));
 const glow=site.accentColor+Math.round(51*site.effectsIntensity).toString(16).padStart(2,'0');
 const anim=(id:string)=>{const a=site.siteAnimations.find(x=>x.id===id&&x.enabled);if(!a)return undefined;const map:Record<string,string>={'hero-float':'float 4s ease-in-out infinite','hero-glow':'pulse 3s ease-in-out infinite','text-shimmer':'shimmer 3s linear infinite','button-pulse':'pulse 2.4s ease-in-out infinite','media-float':'float 6s ease-in-out infinite','background-drift':'drift 12s ease-in-out infinite','particles-drift':'float 8s ease-in-out infinite'};return {animation:map[id],animationDuration:(a.duration||3)+'s'}};
 return <main className='min-h-screen overflow-hidden text-white' style={{backgroundColor:site.backgroundColor,fontFamily:site.headlineFont||'Inter',fontSize:(site.bodySize||1)+'rem'}}><style>{site.customCss||''}</style><style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}@keyframes shimmer{0%{filter:brightness(1)}50%{filter:brightness(1.35)}100%{filter:brightness(1)}}@keyframes drift{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(12px,-8px,0)}}`}</style>
  <section className='relative isolate min-h-screen overflow-hidden border-b border-white/[.06]'>
   <div className='absolute inset-0 -z-20' style={{background:'radial-gradient(circle at 50% -5%,'+glow+',transparent 35%),linear-gradient(180deg,'+site.panelColor+','+site.backgroundColor+' 60%)'}}/>
   {site.mediaLayers.map(m=>{const style:React.CSSProperties={position:'absolute',left:m.x+'%',top:m.y+'%',width:m.width+'%',height:m.height+'%',opacity:m.opacity,zIndex:m.zIndex,transform:'translate(-50%,-50%) rotate('+m.rotation+'deg)',filter:'blur('+m.blur+'px)',objectFit:m.objectFit,pointerEvents:m.clickableUrl?'auto':'none'}; return m.url ? <div key={m.id} className='pointer-events-none absolute inset-0 -z-5 overflow-hidden' style={site.siteAnimations.some(a=>a.id==='media-float'&&a.mediaId===m.id&&a.enabled)?anim('media-float'):undefined}>{m.type==='video'?<video src={m.url} style={style} autoPlay={m.autoplay} loop={m.loop} muted={m.muted} playsInline/>:<img src={m.url} style={style} alt=''/>}</div>:null})}
   {site.grid&&<div className='absolute inset-0 -z-10' style={{opacity:site.gridOpacity,backgroundImage:'linear-gradient(rgba(255,255,255,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.08) 1px,transparent 1px)',backgroundSize:'68px 68px',maskImage:'linear-gradient(to bottom,black,transparent 75%)'}}/>}
   {site.ghostMode&&<div className='pointer-events-none absolute left-1/2 top-1/3 -z-10 h-96 w-96 -translate-x-1/2 rounded-full blur-3xl' style={{background:site.secondaryColor,opacity:site.glowOpacity*.35}}/>}
   {site.particles&&particles.map((p,i)=><span key={i} className='absolute -z-10 h-1 w-1 animate-pulse rounded-full bg-white/40' style={{left:p.left+'%',top:p.top+'%',animationDelay:p.delay+'s'}}/>)}
   {site.announcement&&<div className='relative z-30 mx-auto mt-3 max-w-[1320px] px-4 sm:px-8'><div className='rounded-xl border border-white/10 bg-black/35 px-4 py-2 text-center text-xs text-zinc-300 backdrop-blur-xl'>{site.announcement}</div></div>}<header className='relative z-30 mx-auto max-w-[1320px] px-4 pt-4 sm:px-8 sm:pt-7'>
    <nav className='flex h-[70px] items-center justify-between border border-white/[.09] px-4 backdrop-blur-2xl sm:h-[78px] sm:px-6'>
     <Link to='/' className='text-[22px] font-semibold tracking-[-.06em] sm:text-[25px]'>{site.brandName}<span style={{color:site.accentColor}}>{site.brandTld}</span></Link>
     <div className='hidden items-center gap-1 sm:flex'><a href='#showcase' className='rounded-xl px-4 py-2.5 text-sm text-zinc-400 hover:text-white'>{site.showcaseLabel}</a>{site.featureSection&&<a href='#features' className='rounded-xl px-4 py-2.5 text-sm text-zinc-400 hover:text-white'>{site.featuresLabel}</a>}<Link to='/login' className='rounded-xl px-4 py-2.5 text-sm text-zinc-300 hover:text-white'>{site.signInLabel}</Link><Link to='/register' className='rounded-xl px-4 py-2.5 text-sm font-semibold text-white' style={{backgroundColor:site.accentColor+'22',border:'1px solid '+site.accentColor+'66'}}>{site.createLabel}</Link></div>
     <button type='button' onClick={()=>setMenuOpen(v=>!v)} className='grid h-11 w-11 place-items-center rounded-xl border border-white/10 sm:hidden'>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button>
    </nav>
    {menuOpen&&<div className='mt-2 grid gap-1 rounded-2xl border border-white/10 bg-[#0e0e10] p-2 sm:hidden'><a href='#showcase' onClick={()=>setMenuOpen(false)} className='rounded-xl px-4 py-3 text-sm text-zinc-300'>Showcase</a>{site.featureSection&&<a href='#features' onClick={()=>setMenuOpen(false)} className='rounded-xl px-4 py-3 text-sm text-zinc-300'>Features</a>}<Link to='/login' className='rounded-xl px-4 py-3 text-sm text-zinc-300'>Sign in</Link><Link to='/register' className='rounded-xl px-4 py-3 text-sm font-semibold' style={{color:site.accentColor}}>Create page</Link></div>}
   </header>
   <div className='relative z-10 mx-auto max-w-5xl px-5 pt-24 sm:pt-32' style={{textAlign:site.heroAlignment,...(anim('hero-float')||{}),minHeight:site.heroSize==='fullscreen'?'72vh':site.heroSize==='large'?'60vh':site.heroSize==='standard'?'48vh':'36vh',paddingTop:site.heroSize==='compact'?'72px':undefined}}>
    <div className='mx-auto inline-flex items-center gap-2 rounded-full border px-4 py-2 text-[10px] font-semibold uppercase tracking-[.2em] sm:text-xs' style={{borderColor:site.accentColor+'44',backgroundColor:site.accentColor+'0f',color:site.accentColor}}><Sparkles size={13}/>{site.heroBadge}</div>
    <h1 className='mx-auto mt-7 max-w-5xl font-semibold leading-[.91] tracking-[-.075em]' style={{...anim('text-shimmer'),fontFamily:site.headlineFont||'Inter',fontWeight:site.headlineWeight||600,fontSize:'clamp(3.2rem, '+(site.headlineSize||8)+'vw, 7.4rem)'}}>{site.heroTitle}</h1>
    <p className='mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-400 sm:text-xl sm:leading-8'>{site.heroSubtitle}</p>
    <div className='mt-8 flex flex-col gap-3 sm:flex-row' style={{justifyContent:site.heroAlignment==='left'?'flex-start':site.heroAlignment==='right'?'flex-end':'center'}}><Link to={site.primaryButtonUrl} className='inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl px-7 text-sm font-semibold text-white' style={{backgroundColor:site.accentColor,...(anim('button-pulse')||{})}}>{site.primaryButton}<ArrowRight size={17}/></Link><a href={site.secondaryButtonUrl} className='inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] px-7 text-sm text-zinc-200'>{site.secondaryButton}</a></div>
    {site.showTrustBar&&<div className='mt-4 text-[11px] text-zinc-600'>{site.trustText}</div>}
   </div>
   <div id='showcase' className='mx-auto mt-16 max-w-5xl px-5 pb-20 sm:mt-24'><div className='mx-auto max-w-xl rounded-[30px] border border-white/[.12] bg-black/45 p-5 shadow-2xl backdrop-blur-xl'><div className='h-36 rounded-2xl' style={{background:'radial-gradient(circle at 70% 30%,'+glow+',transparent 35%),'+site.panelColor}}/><div className='mx-auto -mt-10 h-20 w-20 rounded-full border-4 border-[#0b0b0d]' style={{backgroundColor:site.secondaryColor+'33'}}/><p className='mt-3 text-center text-[10px] uppercase tracking-[.18em]' style={{color:site.accentColor}}>your profile</p><h2 className='mt-1 text-center text-2xl font-bold'>{site.showcaseTitle||'Make it yours'}</h2><p className='mt-2 text-center text-xs leading-5 text-zinc-500'>{site.showcaseDescription||''}</p><div className='mt-5 grid gap-2 sm:grid-cols-3'>{['Links','Socials','Music'].map(x=><div key={x} className='rounded-xl border border-white/[.07] bg-white/[.025] p-3 text-center text-xs text-zinc-300'>{x}</div>)}</div></div></div>
  </section>
  {site.featureSection&&<section id='features' className='border-b border-white/[.06] px-5 py-20 sm:px-8 sm:py-28' style={{backgroundColor:site.backgroundColor}}><div className='mx-auto max-w-6xl'><p className='text-[10px] font-semibold uppercase tracking-[.2em]' style={{color:site.accentColor}}>Built for profiles, not templates</p><h2 className='mt-4 text-3xl font-semibold tracking-[-.06em] sm:text-5xl'>{site.featuresTitle||'Everything important is one tap away.'}</h2><p className='mt-3 max-w-2xl text-sm leading-6 text-zinc-500'>{site.featuresDescription||''}</p><div className='mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4'>{[['Links','Add and manage the links people need.'],['Appearance','Backgrounds, fonts, effects and colors.'],['Music','A player that only plays when you allow it.'],['Analytics','See visits and understand your profile.']].map(([title,text])=><article key={title} className='rounded-[24px] border border-white/[.07] p-6' style={{backgroundColor:site.panelColor}}><h3 className='font-semibold'>{title}</h3><p className='mt-2 text-sm leading-6 text-zinc-500'>{text}</p></article>)}</div></div></section>}
  <footer className='px-5 py-8'><div className='mx-auto flex max-w-6xl items-center justify-between text-xs text-zinc-600'><span className='font-semibold text-white'>{site.brandName}<span style={{color:site.accentColor}}>{site.brandTld}</span></span><span>{site.footerText}</span></div></footer>
 </main>;
};
