import React from 'react';
import { Eye, Save } from 'lucide-react';
import { apiService } from '../../../services/api';
import { SiteMediaLayer, SiteSettings, User } from '../../../types';

const defaults:SiteSettings={brandName:'suffer',brandTld:'.info',heroBadge:'A profile platform built around you',heroTitle:'Your entire online identity, in one place.',heroSubtitle:'Build a profile that actually feels like yours. Links, socials, music, effects, badges, backgrounds and more — all controlled from one easy dashboard.',primaryButton:'Create your profile',secondaryButton:'Explore the experience',mediaLayers:[],siteAnimations:[],accentColor:'#ef4444',secondaryColor:'#cbd5e1',backgroundColor:'#050506',panelColor:'#0d0d0f',gridOpacity:.12,glowOpacity:.2,particles:true,grid:true,ghostMode:true,featureSection:true,announcement:'',showcaseLabel:'Showcase',featuresLabel:'Features',signInLabel:'Sign in',createLabel:'Create page',primaryButtonUrl:'/register',secondaryButtonUrl:'#showcase',heroAlignment:'center',seoTitle:'suffer.info',seoDescription:'Create a profile that actually feels like yours.',seoImage:'',footerText:'Your page. Your links. Your rules.',effectsIntensity:1};

export const SiteEditor:React.FC<{user:User}>=({user})=>{
 const [settings,setSettings]=React.useState<SiteSettings>(defaults); const [saving,setSaving]=React.useState(false); const [message,setMessage]=React.useState('');
 React.useEffect(()=>{apiService.getSiteSettings().then(setSettings).catch(e=>setMessage(e instanceof Error?e.message:'Could not load site settings.'));},[]);
 const update=(key:keyof SiteSettings,value:unknown)=>setSettings(s=>({...s,[key]:value}));
 const mediaUpdate=(index:number,patch:Partial<SiteMediaLayer>)=>update('mediaLayers',settings.mediaLayers.map((m,i)=>i===index?{...m,...patch}:m));
 const themes=[
  {name:'Suffer',description:'Signature red / black ghost aesthetic',accentColor:'#ef4444',secondaryColor:'#cbd5e1',backgroundColor:'#050506',panelColor:'#0d0d0f',gridOpacity:.12,glowOpacity:.2,ghostMode:true,particles:true,grid:true,effectsIntensity:1},
  {name:'Blood Moon',description:'Deep crimson with a dramatic night glow',accentColor:'#b91c1c',secondaryColor:'#fecaca',backgroundColor:'#080303',panelColor:'#160708',gridOpacity:.08,glowOpacity:.3,ghostMode:true,particles:true,grid:false,effectsIntensity:1},
  {name:'Ghost',description:'Cold monochrome with a spectral atmosphere',accentColor:'#e5e7eb',secondaryColor:'#94a3b8',backgroundColor:'#05070a',panelColor:'#0c1016',gridOpacity:.1,glowOpacity:.25,ghostMode:true,particles:true,grid:true,effectsIntensity:.8},
  {name:'Void',description:'Minimal black-on-black premium look',accentColor:'#f87171',secondaryColor:'#71717a',backgroundColor:'#020203',panelColor:'#08080a',gridOpacity:.04,glowOpacity:.14,ghostMode:false,particles:false,grid:false,effectsIntensity:.55},
  {name:'Crimson Glass',description:'Bright red accents with glassy panels',accentColor:'#dc2626',secondaryColor:'#f1f5f9',backgroundColor:'#09090b',panelColor:'#121216',gridOpacity:.16,glowOpacity:.22,ghostMode:true,particles:true,grid:true,effectsIntensity:1},
  {name:'Winter',description:'Icy silver and dark blue-black',accentColor:'#93c5fd',secondaryColor:'#e0f2fe',backgroundColor:'#030609',panelColor:'#0a1118',gridOpacity:.1,glowOpacity:.2,ghostMode:true,particles:true,grid:true,effectsIntensity:.75},
 ];
 const applyTheme=(theme:typeof themes[number])=>setSettings(s=>({...s,...theme}));
 const save=async()=>{setSaving(true);setMessage('');try{setSettings(await apiService.updateSiteSettings(settings));setMessage('Site saved. Your public homepage is updated.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save site.');}finally{setSaving(false);}};
 if(user.role!=='owner')return <section className='rounded-2xl border border-red-500/20 bg-red-500/5 p-6'><h2 className='text-lg font-semibold'>Site Editor</h2><p className='mt-2 text-sm text-zinc-400'>Only the site owner can edit global homepage settings.</p></section>;
 return <div className='space-y-5'>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'>
   <div><h2 className='text-lg font-semibold'>Site themes</h2><p className='mt-1 text-sm text-zinc-500'>Start with a complete visual preset, then customize anything you want. Themes only change the homepage appearance.</p></div>
   <div className='mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3'>
    {themes.map(theme=><button key={theme.name} type='button' onClick={()=>applyTheme(theme)} className='group overflow-hidden rounded-2xl border border-white/10 bg-black/20 text-left transition hover:-translate-y-0.5 hover:border-white/20'>
     <div className='h-24 p-4' style={{background:'radial-gradient(circle at 70% 20%,'+theme.accentColor+'55,transparent 45%),'+theme.backgroundColor}}><div className='h-full rounded-xl border border-white/10 p-3' style={{backgroundColor:theme.panelColor}}><div className='h-2 w-16 rounded-full' style={{backgroundColor:theme.accentColor}}/><div className='mt-3 h-2 w-28 rounded-full bg-white/10'/><div className='mt-2 h-2 w-20 rounded-full bg-white/10'/></div></div>
     <div className='p-4'><div className='flex items-center justify-between gap-2'><span className='font-semibold text-white'>{theme.name}</span><span className='text-[10px] font-semibold uppercase tracking-wider' style={{color:theme.accentColor}}>Apply</span></div><p className='mt-1 text-xs leading-5 text-zinc-500'>{theme.description}</p></div>
    </button>)}
   </div>
  </section>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'>
   <div className='flex items-center justify-between gap-3'><div><h2 className='text-lg font-semibold'>Images & videos</h2><p className='mt-1 text-sm text-zinc-500'>Add visual layers anywhere on the homepage without coding.</p></div><button type='button' onClick={()=>update('mediaLayers',[...settings.mediaLayers,{id:crypto.randomUUID(),type:'image',url:'',x:50,y:50,width:70,height:70,opacity:1,blur:0,rotation:0,zIndex:0,objectFit:'cover',autoplay:true,loop:true,muted:true}])} className='rounded-xl bg-red-500 px-4 py-2 text-xs font-semibold'>Add media</button></div>
   <div className='mt-5 space-y-3'>{settings.mediaLayers.map((m,i)=><div key={m.id} className='rounded-2xl border border-white/10 bg-black/20 p-4'>
    <div className='grid gap-3 sm:grid-cols-2'><label className='text-xs text-zinc-500'>Type<select value={m.type} onChange={e=>mediaUpdate(i,{type:e.target.value as SiteMediaLayer['type']})} className='mt-1 h-10 w-full rounded-xl border border-white/10 bg-black/30 px-3 text-sm text-white'><option value='image'>Image</option><option value='video'>Video</option></select></label><label className='text-xs text-zinc-500'>Media URL<input value={m.url} onChange={e=>mediaUpdate(i,{url:e.target.value})} placeholder='https://...' className='mt-1 h-10 w-full rounded-xl border border-white/10 bg-black/30 px-3 text-sm'/></label></div>
    <div className='mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4'><Num label='X position' value={m.x} onChange={v=>mediaUpdate(i,{x:v})}/><Num label='Y position' value={m.y} onChange={v=>mediaUpdate(i,{y:v})}/><Num label='Width' value={m.width} onChange={v=>mediaUpdate(i,{width:v})}/><Num label='Height' value={m.height} onChange={v=>mediaUpdate(i,{height:v})}/><Num label='Opacity' value={m.opacity} onChange={v=>mediaUpdate(i,{opacity:v/100})}/><Num label='Blur' value={m.blur} onChange={v=>mediaUpdate(i,{blur:v})}/><Num label='Rotation' value={m.rotation} onChange={v=>mediaUpdate(i,{rotation:v})}/><Num label='Layer' value={m.zIndex} onChange={v=>mediaUpdate(i,{zIndex:v})}/></div>
    {m.type==='video'&&<div className='mt-3 flex flex-wrap gap-4 text-xs text-zinc-300'><label><input type='checkbox' checked={m.autoplay} onChange={e=>mediaUpdate(i,{autoplay:e.target.checked})}/> Autoplay</label><label><input type='checkbox' checked={m.loop} onChange={e=>mediaUpdate(i,{loop:e.target.checked})}/> Loop</label><label><input type='checkbox' checked={m.muted} onChange={e=>mediaUpdate(i,{muted:e.target.checked})}/> Muted</label></div>}
    <button type='button' onClick={()=>update('mediaLayers',settings.mediaLayers.filter((_,n)=>n!==i))} className='mt-3 rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-300'>Remove</button>
   </div>)}</div>
   <p className='mt-3 text-[11px] text-zinc-600'>Position uses percentages, so you can place each image/video behind any part of the homepage.</p>
  </section>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'>
   <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'><div><h2 className='text-lg font-semibold'>No-code Site Editor</h2><p className='mt-1 text-sm text-zinc-500'>Change the public site without touching GitHub, CSS, or code.</p></div><button type='button' disabled={saving} onClick={save} className='inline-flex items-center gap-2 self-start rounded-xl bg-red-500 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50'><Save size={14}/>{saving?'Saving…':'Save site'}</button></div>
   {message&&<p className='mt-4 rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-zinc-300'>{message}</p>}
   <div className='mt-6 grid gap-6 lg:grid-cols-2'>
    <div className='space-y-4'><h3 className='text-sm font-semibold text-zinc-200'>Brand & text</h3><Field label='Announcement bar' value={settings.announcement} onChange={v=>update('announcement',v)}/><div className='grid gap-3 sm:grid-cols-2'><Field label='Showcase label' value={settings.showcaseLabel} onChange={v=>update('showcaseLabel',v)}/><Field label='Features label' value={settings.featuresLabel} onChange={v=>update('featuresLabel',v)}/><Field label='Sign-in label' value={settings.signInLabel} onChange={v=>update('signInLabel',v)}/><Field label='Create label' value={settings.createLabel} onChange={v=>update('createLabel',v)}/></div><Field label='Brand name' value={settings.brandName} onChange={v=>update('brandName',v)}/><Field label='Brand ending' value={settings.brandTld} onChange={v=>update('brandTld',v)}/><Field label='Top badge' value={settings.heroBadge} onChange={v=>update('heroBadge',v)}/><Field label='Hero headline' value={settings.heroTitle} onChange={v=>update('heroTitle',v)}/><TextArea label='Hero description' value={settings.heroSubtitle} onChange={v=>update('heroSubtitle',v)}/><Field label='Primary button' value={settings.primaryButton} onChange={v=>update('primaryButton',v)}/><Field label='Secondary button' value={settings.secondaryButton} onChange={v=>update('secondaryButton',v)}/><div className='grid gap-3 sm:grid-cols-2'><Field label='Primary button URL' value={settings.primaryButtonUrl} onChange={v=>update('primaryButtonUrl',v)}/><Field label='Secondary button URL' value={settings.secondaryButtonUrl} onChange={v=>update('secondaryButtonUrl',v)}/></div><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>Hero alignment</span><select value={settings.heroAlignment} onChange={e=>update('heroAlignment',e.target.value)} className='h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm'><option value='left'>Left</option><option value='center'>Center</option><option value='right'>Right</option></select></label></div>
    <div className='space-y-4'><h3 className='text-sm font-semibold text-zinc-200'>Colors & atmosphere</h3><div className='grid gap-3 sm:grid-cols-2'><ColorField label='Accent' value={settings.accentColor} onChange={v=>update('accentColor',v)}/><ColorField label='Secondary' value={settings.secondaryColor} onChange={v=>update('secondaryColor',v)}/><ColorField label='Page background' value={settings.backgroundColor} onChange={v=>update('backgroundColor',v)}/><ColorField label='Panel background' value={settings.panelColor} onChange={v=>update('panelColor',v)}/></div><Range label='Grid opacity' value={settings.gridOpacity} onChange={v=>update('gridOpacity',v)}/><Range label='Glow opacity' value={settings.glowOpacity} onChange={v=>update('glowOpacity',v)}/><Toggle label='Ghost atmosphere' value={settings.ghostMode} onChange={v=>update('ghostMode',v)}/><Toggle label='Floating particles' value={settings.particles} onChange={v=>update('particles',v)}/><Toggle label='Background grid' value={settings.grid} onChange={v=>update('grid',v)}/><Toggle label='Feature section' value={settings.featureSection} onChange={v=>update('featureSection',v)}/><Range label='Effects intensity' value={settings.effectsIntensity} onChange={v=>update('effectsIntensity',v)}/></div>
   </div>
  </section>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'><h2 className='text-lg font-semibold'>SEO & footer</h2><p className='mt-1 text-sm text-zinc-500'>Control how the homepage is described and what appears at the bottom.</p><div className='mt-5 grid gap-4 lg:grid-cols-2'><Field label='SEO title' value={settings.seoTitle} onChange={v=>update('seoTitle',v)}/><Field label='SEO image URL' value={settings.seoImage} onChange={v=>update('seoImage',v)}/><TextArea label='SEO description' value={settings.seoDescription} onChange={v=>update('seoDescription',v)}/><TextArea label='Footer text' value={settings.footerText} onChange={v=>update('footerText',v)}/></div></section>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'><div className='flex items-center gap-2'><Eye size={16} className='text-red-300'/><h2 className='font-semibold'>Live preview</h2></div><div className='mt-4 overflow-hidden rounded-2xl border border-white/10 p-5' style={{background:'radial-gradient(circle at 50% -10%, '+settings.accentColor+'33, transparent 35%), '+settings.backgroundColor}}><div className='mx-auto max-w-xl text-center'><div className='text-lg font-bold'>{settings.brandName}<span style={{color:settings.accentColor}}>{settings.brandTld}</span></div><div className='mt-6 inline-flex rounded-full border px-3 py-1 text-[10px] uppercase tracking-widest' style={{borderColor:settings.accentColor+'55',color:settings.accentColor}}>{settings.heroBadge}</div><h3 className='mt-5 text-3xl font-bold tracking-tight'>{settings.heroTitle}</h3><p className='mt-3 text-sm text-zinc-400'>{settings.heroSubtitle}</p><div className='mt-5 flex justify-center gap-2'><span className='rounded-xl px-4 py-2 text-xs font-semibold text-white' style={{backgroundColor:settings.accentColor}}>{settings.primaryButton}</span><span className='rounded-xl border border-white/10 px-4 py-2 text-xs'>{settings.secondaryButton}</span></div></div></div></section>
 </div>;
};
const Field=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className='h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none focus:border-red-400/40'/></label>;
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className='w-full resize-none rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-red-400/40'/></label>;
const ColorField=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><div className='flex gap-2'><input type='color' value={value} onChange={e=>onChange(e.target.value)} className='h-10 w-12 rounded-lg border border-white/10 bg-transparent p-1'/><input value={value} onChange={e=>onChange(e.target.value)} className='h-10 min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-sm'/></div></label>;
const Range=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className='block'><div className='flex justify-between text-xs text-zinc-500'><span>{label}</span><span>{Math.round(value*100)}%</span></div><input className='mt-2 w-full' type='range' min='0' max='1' step='.05' value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const Toggle=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className='flex cursor-pointer items-center justify-between rounded-xl border border-white/10 bg-black/10 px-3 py-3'><span className='text-sm text-zinc-300'>{label}</span><input type='checkbox' checked={value} onChange={e=>onChange(e.target.checked)}/></label>;
const Num=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className='text-[11px] text-zinc-500'>{label}<input type='number' value={value} onChange={e=>onChange(Number(e.target.value))} className='mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-xs text-white'/></label>;
