import React from 'react';
import { Eye, Save, ImagePlus, Sparkles, Trash2, Play, Type, Palette } from 'lucide-react';
import { apiService } from '../../../services/api';
import { SiteMediaLayer, SiteSettings, User } from '../../../types';

const defaults:SiteSettings={brandName:'suffer',brandTld:'.info',heroBadge:'A profile platform built around you',heroTitle:'Your entire online identity, in one place.',heroSubtitle:'Build a profile that actually feels like yours.',primaryButton:'Create your profile',secondaryButton:'Explore the experience',mediaLayers:[],siteAnimations:[],accentColor:'#ef4444',secondaryColor:'#cbd5e1',backgroundColor:'#050506',panelColor:'#0d0d0f',gridOpacity:.12,glowOpacity:.2,particles:true,grid:true,ghostMode:true,featureSection:true,announcement:'',showcaseLabel:'Showcase',featuresLabel:'Features',signInLabel:'Sign in',createLabel:'Create page',primaryButtonUrl:'/register',secondaryButtonUrl:'#showcase',heroAlignment:'center',seoTitle:'suffer.info',seoDescription:'Create a profile that actually feels like yours.',seoImage:'',footerText:'Your page. Your links. Your rules.',effectsIntensity:1,navStyle:'glass',heroSize:'fullscreen',heroWidth:'standard',headlineFont:'Inter',headlineWeight:600,headlineSize:8,bodySize:1,pageRadius:22,sectionSpacing:28,noise:false,vignette:true,scanlines:false,animatedGradient:true,mouseGlow:true,hoverLift:true,buttonStyle:'solid',buttonRadius:16,showTrustBar:true,trustText:'Free to start · No design skills needed · Your profile, your rules.',showcaseTitle:'Make it yours',showcaseDescription:'One editor for your profile, links, music, badges, effects and media.',featuresTitle:'Everything important is one tap away.',featuresDescription:'Powerful controls without making you learn code.',featureCards:[],customCss:''};

const animationPresets=[
 {id:'hero-float',name:'Hero float',target:'site',description:'Gently lifts the hero content.'},
 {id:'hero-glow',name:'Hero glow',target:'site',description:'Breathing accent glow behind the hero.'},
 {id:'text-shimmer',name:'Text shimmer',target:'site',description:'Subtle moving highlight across the headline.'},
 {id:'button-pulse',name:'Button pulse',target:'site',description:'Soft attention pulse on the main button.'},
 {id:'media-float',name:'Media float',target:'media',description:'Makes added images/videos drift naturally.'},
 {id:'background-drift',name:'Background drift',target:'site',description:'Slow atmospheric movement in the background.'},
 {id:'particles-drift',name:'Particle drift',target:'site',description:'Adds a slower floating particle feel.'},
];

export const SiteEditor:React.FC<{user:User}>=({user})=>{
 const [settings,setSettings]=React.useState<SiteSettings>(defaults);
 const [saving,setSaving]=React.useState(false); const [message,setMessage]=React.useState('');
 React.useEffect(()=>{apiService.getSiteSettings().then(s=>setSettings({...defaults,...s,mediaLayers:s.mediaLayers||[],siteAnimations:s.siteAnimations||[]})).catch(e=>setMessage(e instanceof Error?e.message:'Could not load site settings.'));},[]);
 const update=(key:keyof SiteSettings,value:unknown)=>setSettings(s=>({...s,[key]:value}));
 const updateMedia=(id:string,patch:Partial<SiteMediaLayer>)=>update('mediaLayers',settings.mediaLayers.map(m=>m.id===id?{...m,...patch}:m));
 const toggleAnimation=(id:string)=>{
   const existing=settings.siteAnimations.find(a=>a.id===id);
   if(existing){update('siteAnimations',settings.siteAnimations.filter(a=>a.id!==id));return;}
   const preset=animationPresets.find(a=>a.id===id); if(!preset)return;
   update('siteAnimations',[...settings.siteAnimations,{id:preset.id,target:preset.target as 'site'|'media',name:preset.name,duration:3,delay:0,intensity:1,enabled:true}]);
 };
 const readImage=(file:File)=>{
   if(file.size>3*1024*1024){setMessage('Images are limited to 3MB in the visual editor.');return;}
   const reader=new FileReader(); reader.onload=()=>update('mediaLayers',[...settings.mediaLayers,{id:crypto.randomUUID(),type:'image',url:String(reader.result||''),x:50,y:50,width:55,height:40,opacity:1,blur:0,rotation:0,zIndex:0,objectFit:'cover',autoplay:false,loop:false,muted:true}]); reader.readAsDataURL(file);
 };
 const save=async()=>{setSaving(true);setMessage('');try{setSettings(await apiService.updateSiteSettings(settings));setMessage('Saved — the live homepage now uses these settings.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save the site.');}finally{setSaving(false);}};
 if(user.role!=='owner')return <section className="rounded-2xl border border-red-500/20 bg-red-500/5 p-6"><h2 className="text-lg font-semibold">Site Editor</h2><p className="mt-2 text-sm text-zinc-400">Only the site owner can edit global homepage settings.</p></section>;
 return <div className="space-y-5">
  <div className="sticky top-[73px] z-20 flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-[#0b0b0c]/95 p-3 backdrop-blur-xl">
   <div className="flex items-center gap-2"><Eye size={16} className="text-red-300"/><div><p className="text-sm font-semibold">Visual site builder</p><p className="text-[10px] text-zinc-500">Edit the preview and see changes instantly.</p></div></div>
   <button disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-red-500 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><Save size={14}/>{saving?'Saving…':'Publish changes'}</button>
  </div>
  {message&&<div className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-xs text-zinc-300">{message}</div>}
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(340px,.8fr)]">
   <section className="xl:sticky xl:top-[137px] xl:self-start overflow-hidden rounded-3xl border border-white/10 bg-[#080809] shadow-2xl">
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-zinc-600">Live preview</p><p className="mt-1 text-xs text-zinc-400">This is the page visitors will see.</p></div><a href="/" target="_blank" className="rounded-lg border border-white/10 px-3 py-1.5 text-[10px] text-zinc-300">Open live site</a></div>
    <div className="min-h-[620px] overflow-hidden p-5 sm:p-8" style={{background:'radial-gradient(circle at 50% 0%,'+settings.accentColor+'35,transparent 34%),'+settings.backgroundColor}}>
      <div className="mx-auto max-w-2xl" style={{textAlign:settings.heroAlignment}}>
       <div className="text-lg font-bold">{settings.brandName}<span style={{color:settings.accentColor}}>{settings.brandTld}</span></div>
       {settings.announcement&&<div className="mt-4 rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-[10px] text-zinc-400">{settings.announcement}</div>}
       <div className="mt-16 inline-flex rounded-full border px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.18em]" style={{borderColor:settings.accentColor+'55',backgroundColor:settings.accentColor+'12',color:settings.accentColor}}>{settings.heroBadge}</div>
       <h1 className="mt-5 text-4xl font-black tracking-[-.06em] sm:text-6xl" style={{color:'#fff'}}>{settings.heroTitle||'Your headline'}</h1>
       <p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-zinc-400">{settings.heroSubtitle||'Your description'}</p>
       <div className="mt-7 flex flex-wrap gap-2" style={{justifyContent:settings.heroAlignment==='left'?'flex-start':settings.heroAlignment==='right'?'flex-end':'center'}}><span className="rounded-xl px-5 py-3 text-xs font-bold text-white" style={{backgroundColor:settings.accentColor}}>{settings.primaryButton}</span><span className="rounded-xl border border-white/10 bg-white/[.03] px-5 py-3 text-xs font-semibold">{settings.secondaryButton}</span></div>
       <div className="mx-auto mt-14 max-w-lg rounded-3xl border border-white/10 bg-black/35 p-4 backdrop-blur-xl"><div className="h-24 rounded-2xl" style={{background:'radial-gradient(circle at 70% 20%,'+settings.accentColor+'55,transparent 40%),'+settings.panelColor}}/><div className="mx-auto -mt-7 h-14 w-14 rounded-full border-4 border-[#0b0b0d]" style={{backgroundColor:settings.secondaryColor+'33'}}/><p className="mt-2 text-center text-[9px] uppercase tracking-widest" style={{color:settings.accentColor}}>profile preview</p><div className="mt-3 grid grid-cols-3 gap-2">{['Links','Music','Badges'].map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-[9px] text-zinc-400">{x}</div>)}</div></div>
      </div>
    </div>
   </section>
   <div className="space-y-4">
    <Panel icon={<Type size={15}/>} title="Edit text" description="Click a field, type what you want, and the preview updates immediately.">
      <Field label="Brand name" value={settings.brandName} onChange={v=>update('brandName',v)}/><Field label="Brand ending" value={settings.brandTld} onChange={v=>update('brandTld',v)}/><Field label="Announcement" value={settings.announcement} onChange={v=>update('announcement',v)}/><Field label="Hero badge" value={settings.heroBadge} onChange={v=>update('heroBadge',v)}/><Field label="Headline" value={settings.heroTitle} onChange={v=>update('heroTitle',v)}/><TextArea label="Description" value={settings.heroSubtitle} onChange={v=>update('heroSubtitle',v)}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Primary button" value={settings.primaryButton} onChange={v=>update('primaryButton',v)}/><Field label="Secondary button" value={settings.secondaryButton} onChange={v=>update('secondaryButton',v)}/></div><Select label="Hero alignment" value={settings.heroAlignment} onChange={v=>update('heroAlignment',v as SiteSettings['heroAlignment'])} options={['left','center','right']}/>
    </Panel>
    <Panel icon={<Palette size={15}/>} title="Background & atmosphere" description="Change the page mood without touching CSS.">
      <div className="grid gap-3 sm:grid-cols-2"><ColorField label="Background" value={settings.backgroundColor} onChange={v=>update('backgroundColor',v)}/><ColorField label="Accent" value={settings.accentColor} onChange={v=>update('accentColor',v)}/><ColorField label="Panel" value={settings.panelColor} onChange={v=>update('panelColor',v)}/><ColorField label="Secondary" value={settings.secondaryColor} onChange={v=>update('secondaryColor',v)}/></div>
      <Range label="Glow strength" value={settings.glowOpacity} onChange={v=>update('glowOpacity',v)}/><Range label="Grid strength" value={settings.gridOpacity} onChange={v=>update('gridOpacity',v)}/><Range label="Overall effects" value={settings.effectsIntensity} onChange={v=>update('effectsIntensity',v)}/><div className="grid gap-2 sm:grid-cols-3"><Toggle label="Grid" value={settings.grid} onChange={v=>update('grid',v)}/><Toggle label="Particles" value={settings.particles} onChange={v=>update('particles',v)}/><Toggle label="Ghost glow" value={settings.ghostMode} onChange={v=>update('ghostMode',v)}/></div>
    </Panel>
    <Panel icon={<ImagePlus size={15}/>} title="Images & video" description="Upload an image directly or use a URL. The preview updates before you publish.">
      <label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed border-white/15 bg-black/20 px-4 py-6 text-sm text-zinc-300 hover:border-red-500/40"><ImagePlus size={18}/><span>Add image from your device<input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/svg+xml" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)readImage(f)}}/></span></label>
      <button type="button" onClick={()=>update('mediaLayers',[...settings.mediaLayers,{id:crypto.randomUUID(),type:'video',url:'',x:50,y:50,width:100,height:100,opacity:.5,blur:0,rotation:0,zIndex:-1,objectFit:'cover',autoplay:true,loop:true,muted:true}])} className="w-full rounded-xl border border-white/10 px-3 py-2 text-xs text-zinc-300">Add video URL layer</button>
      {settings.mediaLayers.map(m=><div key={m.id} className="rounded-2xl border border-white/10 bg-black/20 p-3"><div className="flex items-center gap-2"><span className="flex-1 truncate text-xs font-semibold">{m.type==='image'?'Image layer':'Video layer'}</span><button onClick={()=>update('mediaLayers',settings.mediaLayers.filter(x=>x.id!==m.id))} className="text-zinc-600 hover:text-red-400"><Trash2 size={14}/></button></div>{m.type==='video'&&<Field label="Video URL" value={m.url} onChange={v=>updateMedia(m.id,{url:v})}/>}<div className="mt-3 grid grid-cols-2 gap-2"><Num label="X %" value={m.x} onChange={v=>updateMedia(m.id,{x:v})}/><Num label="Y %" value={m.y} onChange={v=>updateMedia(m.id,{y:v})}/><Num label="Width %" value={m.width} onChange={v=>updateMedia(m.id,{width:v})}/><Num label="Height %" value={m.height} onChange={v=>updateMedia(m.id,{height:v})}/><Num label="Opacity %" value={m.opacity*100} onChange={v=>updateMedia(m.id,{opacity:v/100})}/><Num label="Blur" value={m.blur} onChange={v=>updateMedia(m.id,{blur:v})}/></div></div>)}
    </Panel>
    <Panel icon={<Sparkles size={15}/>} title="Animations" description="Turn effects on/off with one tap. No code, no CSS, no separate editor.">
      <div className="space-y-2">{animationPresets.map(a=>{const on=settings.siteAnimations.some(x=>x.id===a.id);return <button key={a.id} onClick={()=>toggleAnimation(a.id)} className={'flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition '+(on?'border-red-500/40 bg-red-500/[.07]':'border-white/10 bg-black/20')}><span className={'grid h-9 w-9 place-items-center rounded-xl '+(on?'bg-red-500/15 text-red-300':'bg-white/5 text-zinc-500')}><Play size={14}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{a.name}</span><span className="mt-0.5 block text-[10px] text-zinc-500">{a.description}</span></span><span className="text-[10px] uppercase tracking-widest text-zinc-600">{on?'On':'Off'}</span></button>})}</div>
    </Panel>
<Panel icon={<Sparkles size={15}/>} title="Advanced layout & motion" description="Control the structure, typography, buttons and atmosphere from the same visual editor.">
      <div className="grid gap-3 sm:grid-cols-2"><Select label="Navigation style" value={settings.navStyle||'glass'} onChange={v=>update('navStyle',v)} options={['glass','solid','minimal','floating']}/><Select label="Hero height" value={settings.heroSize||'fullscreen'} onChange={v=>update('heroSize',v)} options={['compact','standard','large','fullscreen']}/><Select label="Content width" value={settings.heroWidth||'standard'} onChange={v=>update('heroWidth',v)} options={['narrow','standard','wide']}/><Select label="Button style" value={settings.buttonStyle||'solid'} onChange={v=>update('buttonStyle',v)} options={['solid','glass','outline','pill']}/></div>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Headline font" value={settings.headlineFont||'Inter'} onChange={v=>update('headlineFont',v)}/><Num label="Headline weight" value={settings.headlineWeight||600} onChange={v=>update('headlineWeight',v)}/><Range label="Headline size" value={(settings.headlineSize||8)/12} onChange={v=>update('headlineSize',Math.round(v*12*10)/10)}/><Range label="Body size" value={(settings.bodySize||1)/1.4} onChange={v=>update('bodySize',Math.max(.8,Math.round(v*1.4*100)/100))}/></div>
      <Range label="Page corner radius" value={(settings.pageRadius||22)/48} onChange={v=>update('pageRadius',Math.round(v*48))}/><Range label="Section spacing" value={(settings.sectionSpacing||28)/64} onChange={v=>update('sectionSpacing',Math.round(v*64))}/><Range label="Button radius" value={(settings.buttonRadius||16)/40} onChange={v=>update('buttonRadius',Math.round(v*40))}/>
      <div className="grid gap-2 sm:grid-cols-2"><Toggle label="Animated gradient" value={!!settings.animatedGradient} onChange={v=>update('animatedGradient',v)}/><Toggle label="Mouse glow" value={!!settings.mouseGlow} onChange={v=>update('mouseGlow',v)}/><Toggle label="Hover lift" value={!!settings.hoverLift} onChange={v=>update('hoverLift',v)}/><Toggle label="Vignette" value={!!settings.vignette} onChange={v=>update('vignette',v)}/><Toggle label="Film noise" value={!!settings.noise} onChange={v=>update('noise',v)}/><Toggle label="Scanlines" value={!!settings.scanlines} onChange={v=>update('scanlines',v)}/></div>
    </Panel>
    <Panel icon={<Type size={15}/>} title="Showcase & content" description="Edit the sections themselves instead of settling for fixed text.">
      <Field label="Showcase title" value={settings.showcaseTitle||''} onChange={v=>update('showcaseTitle',v)}/><TextArea label="Showcase description" value={settings.showcaseDescription||''} onChange={v=>update('showcaseDescription',v)}/><Field label="Features title" value={settings.featuresTitle||''} onChange={v=>update('featuresTitle',v)}/><TextArea label="Features description" value={settings.featuresDescription||''} onChange={v=>update('featuresDescription',v)}/><Toggle label="Show trust bar" value={!!settings.showTrustBar} onChange={v=>update('showTrustBar',v)}/><Field label="Trust bar text" value={settings.trustText||''} onChange={v=>update('trustText',v)}/><TextArea label="Custom CSS (advanced)" value={settings.customCss||''} onChange={v=>update('customCss',v)}/>
    </Panel>
    <Panel icon={<Sparkles size={15}/>} title="Sections & SEO" description="Control what appears below the hero and how the site is described.">
      <Toggle label="Show feature section" value={settings.featureSection} onChange={v=>update('featureSection',v)}/><Field label="Showcase label" value={settings.showcaseLabel} onChange={v=>update('showcaseLabel',v)}/><Field label="Features label" value={settings.featuresLabel} onChange={v=>update('featuresLabel',v)}/><Field label="Footer text" value={settings.footerText} onChange={v=>update('footerText',v)}/><Field label="SEO title" value={settings.seoTitle} onChange={v=>update('seoTitle',v)}/><TextArea label="SEO description" value={settings.seoDescription} onChange={v=>update('seoDescription',v)}/>
    </Panel>
   </div>
  </div>
 </div>;
};

const Panel=({icon,title,description,children}:{icon:React.ReactNode;title:string;description:string;children:React.ReactNode})=><section className="rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5"><div className="flex items-center gap-2 text-red-300">{icon}<h2 className="text-sm font-bold text-white">{title}</h2></div><p className="mt-1 text-xs leading-5 text-zinc-500">{description}</p><div className="mt-4 space-y-3">{children}</div></section>;
const Field=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none focus:border-red-500/50"/></label>;
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className="w-full resize-none rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-red-500/50"/></label>;
const ColorField=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-12 rounded-lg border border-white/10 bg-transparent p-1"/><input value={value} onChange={e=>onChange(e.target.value)} className="h-10 min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-sm"/></div></label>;
const Range=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className="block rounded-xl border border-white/10 bg-black/20 p-3"><div className="flex justify-between text-[11px] text-zinc-500"><span>{label}</span><span>{Math.round(value*100)}%</span></div><input className="mt-2 w-full accent-red-500" type="range" min="0" max="1" step=".05" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const Toggle=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className="flex cursor-pointer items-center justify-between rounded-xl border border-white/10 bg-black/20 px-3 py-3"><span className="text-xs text-zinc-300">{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>;
const Num=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className="text-[10px] text-zinc-500">{label}<input type="number" value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-xs text-white"/></label>;
