import React from 'react';
import { Eye, Save, RotateCcw } from 'lucide-react';
import { apiService } from '../../../services/api';
import { SiteSettings, User } from '../../../types';

const defaults:SiteSettings={brandName:'lost',brandTld:'.lol',heroBadge:'A profile platform built around you',heroTitle:'Your entire online identity, in one place.',heroSubtitle:'Build a profile that actually feels like yours. Links, socials, music, effects, badges, backgrounds and more — all controlled from one easy dashboard.',primaryButton:'Create your profile',secondaryButton:'Explore the experience',accentColor:'#ef4444',secondaryColor:'#cbd5e1',backgroundColor:'#050506',panelColor:'#0d0d0f',gridOpacity:.12,glowOpacity:.2,particles:true,grid:true,ghostMode:true,featureSection:true};

export const SiteEditor:React.FC<{user:User}>=({user})=>{
 const [settings,setSettings]=React.useState<SiteSettings>(defaults); const [saving,setSaving]=React.useState(false); const [message,setMessage]=React.useState('');
 React.useEffect(()=>{apiService.getSiteSettings().then(setSettings).catch(e=>setMessage(e instanceof Error?e.message:'Could not load site settings.'));},[]);
 const update=(key:keyof SiteSettings,value:unknown)=>setSettings(s=>({...s,[key]:value}));
 const save=async()=>{setSaving(true);setMessage('');try{setSettings(await apiService.updateSiteSettings(settings));setMessage('Site saved. Your public homepage is updated.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save site.');}finally{setSaving(false);}};
 if(user.role!=='owner')return <section className='rounded-2xl border border-red-500/20 bg-red-500/5 p-6'><h2 className='text-lg font-semibold'>Site Editor</h2><p className='mt-2 text-sm text-zinc-400'>Only the site owner can edit global homepage settings.</p></section>;
 return <div className='space-y-5'>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'>
   <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'><div><h2 className='text-lg font-semibold'>No-code Site Editor</h2><p className='mt-1 text-sm text-zinc-500'>Change the public site without touching GitHub, CSS, or code.</p></div><button type='button' disabled={saving} onClick={save} className='inline-flex items-center gap-2 self-start rounded-xl bg-red-500 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50'><Save size={14}/>{saving?'Saving…':'Save site'}</button></div>
   {message&&<p className='mt-4 rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-zinc-300'>{message}</p>}
   <div className='mt-6 grid gap-6 lg:grid-cols-2'>
    <div className='space-y-4'><h3 className='text-sm font-semibold text-zinc-200'>Brand & text</h3><Field label='Brand name' value={settings.brandName} onChange={v=>update('brandName',v)}/><Field label='Brand ending' value={settings.brandTld} onChange={v=>update('brandTld',v)}/><Field label='Top badge' value={settings.heroBadge} onChange={v=>update('heroBadge',v)}/><Field label='Hero headline' value={settings.heroTitle} onChange={v=>update('heroTitle',v)}/><TextArea label='Hero description' value={settings.heroSubtitle} onChange={v=>update('heroSubtitle',v)}/><Field label='Primary button' value={settings.primaryButton} onChange={v=>update('primaryButton',v)}/><Field label='Secondary button' value={settings.secondaryButton} onChange={v=>update('secondaryButton',v)}/></div>
    <div className='space-y-4'><h3 className='text-sm font-semibold text-zinc-200'>Colors & atmosphere</h3><div className='grid gap-3 sm:grid-cols-2'><ColorField label='Accent' value={settings.accentColor} onChange={v=>update('accentColor',v)}/><ColorField label='Secondary' value={settings.secondaryColor} onChange={v=>update('secondaryColor',v)}/><ColorField label='Page background' value={settings.backgroundColor} onChange={v=>update('backgroundColor',v)}/><ColorField label='Panel background' value={settings.panelColor} onChange={v=>update('panelColor',v)}/></div><Range label='Grid opacity' value={settings.gridOpacity} onChange={v=>update('gridOpacity',v)}/><Range label='Glow opacity' value={settings.glowOpacity} onChange={v=>update('glowOpacity',v)}/><Toggle label='Ghost atmosphere' value={settings.ghostMode} onChange={v=>update('ghostMode',v)}/><Toggle label='Floating particles' value={settings.particles} onChange={v=>update('particles',v)}/><Toggle label='Background grid' value={settings.grid} onChange={v=>update('grid',v)}/><Toggle label='Feature section' value={settings.featureSection} onChange={v=>update('featureSection',v)}/></div>
   </div>
  </section>
  <section className='rounded-2xl border border-white/[.07] bg-[#0e0e10] p-5 sm:p-6'><div className='flex items-center gap-2'><Eye size={16} className='text-red-300'/><h2 className='font-semibold'>Live preview</h2></div><div className='mt-4 overflow-hidden rounded-2xl border border-white/10 p-5' style={{background:'radial-gradient(circle at 50% -10%, '+settings.accentColor+'33, transparent 35%), '+settings.backgroundColor}}><div className='mx-auto max-w-xl text-center'><div className='text-lg font-bold'>{settings.brandName}<span style={{color:settings.accentColor}}>{settings.brandTld}</span></div><div className='mt-6 inline-flex rounded-full border px-3 py-1 text-[10px] uppercase tracking-widest' style={{borderColor:settings.accentColor+'55',color:settings.accentColor}}>{settings.heroBadge}</div><h3 className='mt-5 text-3xl font-bold tracking-tight'>{settings.heroTitle}</h3><p className='mt-3 text-sm text-zinc-400'>{settings.heroSubtitle}</p><div className='mt-5 flex justify-center gap-2'><span className='rounded-xl px-4 py-2 text-xs font-semibold text-white' style={{backgroundColor:settings.accentColor}}>{settings.primaryButton}</span><span className='rounded-xl border border-white/10 px-4 py-2 text-xs'>{settings.secondaryButton}</span></div></div></div></section>
 </div>;
};
const Field=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className='h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm outline-none focus:border-red-400/40'/></label>;
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className='w-full resize-none rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-red-400/40'/></label>;
const ColorField=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className='block'><span className='mb-1.5 block text-xs text-zinc-500'>{label}</span><div className='flex gap-2'><input type='color' value={value} onChange={e=>onChange(e.target.value)} className='h-10 w-12 rounded-lg border border-white/10 bg-transparent p-1'/><input value={value} onChange={e=>onChange(e.target.value)} className='h-10 min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-sm'/></div></label>;
const Range=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label className='block'><div className='flex justify-between text-xs text-zinc-500'><span>{label}</span><span>{Math.round(value*100)}%</span></div><input className='mt-2 w-full' type='range' min='0' max='1' step='.05' value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const Toggle=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className='flex cursor-pointer items-center justify-between rounded-xl border border-white/10 bg-black/10 px-3 py-3'><span className='text-sm text-zinc-300'>{label}</span><input type='checkbox' checked={value} onChange={e=>onChange(e.target.checked)}/></label>;