import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { FaDiscord, FaGithub, FaInstagram, FaSpotify, FaTiktok, FaTwitch, FaYoutube, FaXTwitter } from 'react-icons/fa6';
import { Globe, Linkedin, Mail, BadgeCheck, Disc3, Eye, MapPin, MessageCircle, Sparkles, AudioLines, ArrowUpRight, Pause, Play } from 'lucide-react';
import { API_URL } from '@/services/api';
import './template.css';

interface BadgeDefinition { name:string; image?:string; fontFamily?:string; textColor?:string; accentColor?:string; animation?:string; description?:string }
interface UserProfile {
 id:number; username:string; name:string; description:string|null; profilePicture:string|null; accentColor?:string; textColor?:string; backgroundColor?:string; backgroundMedia:string|null; backgroundType:'image'|'video'|null;
 usernameEffect?:string; backgroundEffect?:string; cursorEffect?:string; fontFamily?:string; customFontFamily?:string; customFontUrl?:string; verified?:boolean; customEmojis?:Array<{name:string;value:string}>;
 profileOpacity?:number; profileBlur?:number; backgroundOpacity?:number; cardOpacity?:number; cardBlur?:number; audioUrl?:string; audioTitle?:string; audioAutoplay?:boolean; audioCoverUrl?:string;
 totalVisit?:number; location?:string; showLocation?:boolean; showDiscordPresence?:boolean; discordUsername?:string; discordAvatar?:string; badges?:string[]; badgeDefinitions?:BadgeDefinition[]; aliases?:string[];
 role?:'owner'|'co-owner'|'staff'|'member'; roleLabel?:string; profileLayout?:string; cardStyle?:string; cardRadius?:number; linkRadius?:number; linkSpacing?:number; linkOpacity?:number; linkBlur?:number; avatarSize?:number; avatarShape?:string; avatarGlow?:boolean; showViews?:boolean; showStatus?:boolean; showBranding?:boolean; accentGlow?:number;
 pageEnterEffect?:string; clickEffect?:string; cursorTrailSize?:number; particleEffect?:string; typewriterEnabled?:boolean; typewriterTexts?:string[]; typewriterSpeed?:number; typewriterLoop?:boolean; pageEnterText?:string; pageClickSound?:string; metadataTitle?:string; metadataDescription?:string; metadataImage?:string; animatedTitle?:boolean; monochromeIcons?:boolean; customCss?:string;
 links:Array<{_id?:string;id?:number;title:string;url:string}>;
}
const normalizeLinkUrl=(raw:string):string|null=>{const v=raw.trim();if(!v)return null;if(/^mailto:/i.test(v))return v;try{const p=new URL(/^(https?:\/\/)/i.test(v)?v:'https://'+v.replace(/^\/\//,''));return ['http:','https:'].includes(p.protocol)?p.href:null}catch{return null}};
const getLinkIcon=(url:string)=>{const d=url.toLowerCase();if(d.includes('discord'))return FaDiscord;if(d.includes('instagram'))return FaInstagram;if(d.includes('spotify'))return FaSpotify;if(d.includes('tiktok'))return FaTiktok;if(d.includes('twitch'))return FaTwitch;if(d.includes('youtube'))return FaYoutube;if(d.includes('github'))return FaGithub;if(d.includes('x.com')||d.includes('twitter'))return FaXTwitter;if(d.includes('linkedin'))return Linkedin;if(d.startsWith('mailto:'))return Mail;return Globe};

const ProfilePage:React.FC=()=>{
 const {username}=useParams<{username:string}>();const navigate=useNavigate();const [profile,setProfile]=useState<UserProfile|null>(null);const [loading,setLoading]=useState(true);const [entered,setEntered]=useState(false);const [muted,setMuted]=useState(true);const [isVideoPlaying,setIsVideoPlaying]=useState(false);const [seed,setSeed]=useState(1);const [typewriterText,setTypewriterText]=useState('');const videoRef=useRef<HTMLVideoElement|null>(null);const cursorRef=useRef<HTMLCanvasElement|null>(null);
 useEffect(()=>{let active=true;fetch(API_URL+'/users/'+username).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(active)setProfile(d)}).catch(()=>{if(active)toast.error('Failed to load profile')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[username]);
 useEffect(()=>{if(!profile)return;document.title=profile.metadataTitle||'@'+profile.username+' | suffer.info';const m=document.querySelector('meta[name="description"]') as HTMLMetaElement|null;if(m)m.content=profile.metadataDescription||profile.description||'';if(profile.metadataImage){let og=document.querySelector('meta[property="og:image"]') as HTMLMetaElement|null;if(!og){og=document.createElement('meta');og.setAttribute('property','og:image');document.head.appendChild(og)}og.content=profile.metadataImage}},[profile]);
 useEffect(()=>{if(profile?.usernameEffect!=='noise')return;const t=window.setInterval(()=>setSeed(Math.floor(Math.random()*9999)),40);return()=>window.clearInterval(t)},[profile?.usernameEffect]);
 useEffect(()=>{if(!profile?.typewriterEnabled||!(profile.typewriterTexts||[]).length){setTypewriterText('');return}const texts=profile.typewriterTexts||[];let idx=0,pos=0,deleting=false,timer:number;const tick=()=>{const target=texts[idx]||'';if(!deleting){setTypewriterText(target.slice(0,pos++));if(pos>target.length){deleting=true;timer=window.setTimeout(tick,1800);return}}else{setTypewriterText(target.slice(0,pos--));if(pos<0){pos=0;deleting=false;idx=(idx+1)%texts.length;timer=window.setTimeout(tick,500);return}}timer=window.setTimeout(tick,deleting?35:Math.max(20,profile.typewriterSpeed||70))};tick();return()=>window.clearTimeout(timer)},[profile?.typewriterEnabled,profile?.typewriterTexts,profile?.typewriterSpeed]);
 useEffect(()=>{if(!entered||profile?.cursorEffect==='none')return;const canvas=cursorRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,mx=-999,my=-999,lx=-999,ly=-999;let dots:Array<{x:number;y:number;vx:number;vy:number;life:number;size:number}>=[];const move=(e:MouseEvent)=>{mx=e.clientX;my=e.clientY};const resize=()=>{canvas.width=window.innerWidth;canvas.height=window.innerHeight};const star=(x:number,y:number,s:number)=>{ctx.beginPath();ctx.moveTo(x,y-s);ctx.quadraticCurveTo(x+s*.2,y-s*.2,x+s,y);ctx.quadraticCurveTo(x+s*.2,y+s*.2,x,y+s);ctx.quadraticCurveTo(x-s*.2,y+s*.2,x-s,y);ctx.quadraticCurveTo(x-s*.2,y-s*.2,x,y-s);ctx.fill()};const draw=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);if(mx!==lx||my!==ly){for(let i=0;i<4;i++)dots.push({x:mx,y:my,vx:(Math.random()-.5)*1.2,vy:(Math.random()-.5)*1.2,life:1,size:1.5+Math.random()*2});lx=mx;ly=my}dots.forEach(d=>{d.x+=d.vx;d.y+=d.vy;d.life-=1/30;ctx.globalAlpha=Math.max(0,d.life);ctx.fillStyle=profile?.cursorEffect==='red'?'#ef3340':'#ffd87a';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=8;star(d.x,d.y,d.size*d.life)});dots=dots.filter(d=>d.life>0);ctx.globalAlpha=1;ctx.shadowBlur=0;raf=requestAnimationFrame(draw)};resize();window.addEventListener('resize',resize);window.addEventListener('mousemove',move,{passive:true});raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('mousemove',move)}},[entered,profile?.cursorEffect]);
 if(loading)return <div className="template-profile" style={{display:'grid',placeItems:'center'}}>Loading profile</div>;
 if(!profile)return <div className="template-profile" style={{display:'grid',placeItems:'center',textAlign:'center',padding:24}}><div><h1>This profile isn’t here.</h1><button onClick={()=>navigate('/')} style={{marginTop:18,padding:'10px 16px',borderRadius:20}}>Back to suffer.info</button></div></div>;
 const accent=profile.accentColor||'#acc8ff';const text=profile.textColor||'#fff';const aliases=(profile.aliases||[]).slice(0,2);const cardRadius=Math.max(0,Math.min(85,profile.cardRadius??85));const avatarSize=Math.max(64,Math.min(180,profile.avatarSize??118));const linkRadius=Math.max(0,Math.min(32,profile.linkRadius??14));const linkSpacing=Math.max(4,Math.min(28,profile.linkSpacing??14));const linkOpacity=Math.max(.01,Math.min(.2,profile.linkOpacity??.035));const linkBlur=Math.max(0,Math.min(30,profile.linkBlur??5));const cardOpacity=Math.max(.03,Math.min(1,profile.cardOpacity??.03));const cardBlur=Math.max(0,Math.min(30,profile.cardBlur??5));const bgOpacity=Math.max(.1,Math.min(1,profile.backgroundOpacity??1));const validLinks=profile.links.map(l=>({...l,safeUrl:normalizeLinkUrl(l.url)})).filter(l=>l.safeUrl);
 const reveal=async()=>{setEntered(true);const v=videoRef.current;if(v){v.muted=false;setMuted(false);try{await v.play()}catch{setMuted(true)}}};const toggleSound=async()=>{const v=videoRef.current;if(!v)return;v.muted=!v.muted;setMuted(v.muted);if(v.paused)try{await v.play()}catch{}};const toggleVideo=async()=>{const v=videoRef.current;if(!v)return;if(v.paused){try{await v.play();setIsVideoPlaying(true)}catch{}}else{v.pause();setIsVideoPlaying(false)}};
 const usernameAnimation=usernameEffect==='pulse'?{scale:[1,1.04,1]}:usernameEffect==='float'?{y:[0,-5,0]}:usernameEffect==='shake'?{x:[0,-3,3,-2,2,0]}:usernameEffect==='bounce'?{y:[0,-10,0,-5,0]}:usernameEffect==='tilt'?{rotate:[-2,2,-1,1,0]}:usernameEffect==='zoom'?{scale:[1,1.08,1]}:usernameEffect==='neon'?{textShadow:['0 0 4px #fff,0 0 12px '+accent,'0 0 14px '+accent+',0 0 28px '+accent,'0 0 4px #fff,0 0 12px '+accent]}:{};
 const usernameTransition=usernameEffect==='none'?{}:{duration:2.2,repeat:Infinity,ease:'easeInOut' as const};
 const backgroundClass=backgroundEffect==='aurora'?'animate-pulse':backgroundEffect==='pulse'?'animate-[pulse_4s_ease-in-out_infinite]':'';const backgroundGfx=backgroundEffect==='grid'?'bg-[linear-gradient(rgba(239,51,64,.10)_1px,transparent_1px),linear-gradient(90deg,rgba(239,51,64,.10)_1px,transparent_1px)] bg-[size:42px_42px]':backgroundEffect==='vignette'?'bg-[radial-gradient(circle,transparent_35%,rgba(0,0,0,.72)_100%)]':'';
 return <main className={'template-profile '+(cursorEffect==='red'?'cursor-none':'')} style={{backgroundColor:profile.backgroundColor||'#080808',color:text,fontFamily:profile.customFontFamily||profile.fontFamily||'Inter',overflowY:'auto'}}>
   {profile.customFontUrl&&<style>{'@font-face{font-family:LostCustom;src:url('+JSON.stringify(profile.customFontUrl)+');font-display:swap}'}</style>}
   {profile.backgroundMedia&&profile.backgroundType==='video'&&<video ref={videoRef} className="template-bg-video" loop playsInline muted={muted} onPlay={()=>setIsVideoPlaying(true)} onPause={()=>setIsVideoPlaying(false)}><source src={profile.backgroundMedia} type="video/mp4"/></video>}
   {profile.backgroundMedia&&profile.backgroundType==='image'&&<div className="template-bg-video" style={{backgroundImage:'url('+profile.backgroundMedia+')',backgroundSize:'cover',backgroundPosition:'center',opacity:bgOpacity}}/>}
   <div aria-hidden="true" className={'template-canvas '+backgroundClass+' '+backgroundGfx} style={{opacity:bgOpacity}}/>
   {entered&&cursorEffect!=='none'&&<canvas ref={cursorRef} className="template-canvas template-cursor"/>}
   {!entered&&<div className="template-entry" onClick={reveal}><div className="template-entry-symbol">⛧</div></div>}
   <button className="template-volume" onClick={toggleSound} aria-label="Toggle sound">{muted?'🔇':'🔊'}</button>
   {profile.backgroundType==='video'&&backgroundMedia&&entered&&<button onClick={toggleVideo} className="absolute right-5 top-16 z-10 rounded-xl border border-white/10 bg-black/55 px-3 py-2 text-xs text-white backdrop-blur-xl">{isVideoPlaying?'Pause motion':'Play motion'}</button>}
   <motion.section initial={{opacity:0,y:12}} animate={entered?{opacity:1,y:0}:undefined} transition={{duration:.55}} className={'template-card '+(entered?'revealed':'')} style={{maxWidth:'44rem',borderRadius:cardRadius,background:profile.cardStyle==='solid'?'#080808':'rgba(200,27,27,'+cardOpacity+')',backdropFilter:'blur('+cardBlur+'px)'}}>
    <div className="template-main">
      <div className="template-avatar-wrap" style={{width:avatarSize,height:avatarSize}}><img className="template-avatar" src={profilePicture||'/p.png'} alt="avatar"/></div>
      <div className="template-info"><div className="template-name-row"><div className="template-name-wrap"><motion.span animate={usernameAnimation} transition={usernameTransition} className="template-name" style={{color:accent,textShadow:'0 0 16.5px '+accent,filter:usernameEffect==='noise'?'url(#name-filter)':'none'}}>{name}</motion.span><span className="template-tooltip">{profileUsername}</span></div>{profile.badges?.length?<div className="template-badges">{profile.badges.slice(0,8).map(b=>{const d=profile.badgeDefinitions?.find(x=>x.name===b);return <span key={b} className="template-badge" title={d?.description||b}>{d?.image?<img src={d.image} alt={b}/>:<BadgeCheck size={22} color={d?.accentColor||accent}/>}<span className="template-badge-tooltip">{b}</span></span>})}</div>:null}</div>{typewriterText?<div className="template-status">{typewriterText}</div>:description?<div className="template-status" style={{fontSize:14}}>{description}</div>:null}</div>
    </div>
    {profile.showDiscordPresence&&profile.discordUsername&&<div className="template-discord"><div className="template-discord-avatar"><img src={profile.discordAvatar||'/p.png'} alt="Discord avatar"/></div><div className="template-discord-info"><span className="template-discord-user">{profile.discordUsername}</span><span className="template-discord-activity">Connected to Discord</span></div></div>}
    <div className="template-links">{validLinks.map(l=>{const I=getLinkIcon(l.url);return <a key={l._id||l.id||l.url} href={l.safeUrl} target="_blank" rel="noopener noreferrer" title={l.title}><I className="template-link-icon" style={{color:accent}}/></a>})}</div>
    {(aliases.length||profile.role&&profile.role!=='member'||audioUrl||validLinks.length>0)&&<div className="template-extra">
      {aliases.length>0&&<div style={{display:'flex',justifyContent:'center',gap:8,flexWrap:'wrap',marginBottom:8}}>{aliases.map(a=><a key={a} href={'/'+a} style={{color:accent,textDecoration:'none',fontSize:11}}>@{a}</a>)}</div>}
      {profile.role&&profile.role!=='member'&&<div style={{textAlign:'center',fontSize:10,color:accent,textTransform:'uppercase',marginBottom:8}}>{profile.roleLabel||profile.role}</div>}
      {profile.audioUrl&&<div className="template-audio"><audio src={profile.audioUrl} autoPlay={profile.audioAutoplay} controls/></div>}
      {validLinks.length>0&&<div className="template-extra-links" style={{gap:linkSpacing}}>{validLinks.map(l=><a key={l._id||l.id||l.url} className="template-extra-link" href={l.safeUrl} target="_blank" rel="noopener noreferrer" style={{borderRadius:linkRadius,background:'rgba(255,255,255,'+linkOpacity+')',backdropFilter:'blur('+linkBlur+'px)'}}>{l.title}</a>)}</div>}
    </div>}
    <div className="template-footer">{profile.showViews!==false&&<span><Eye size={12}/> {(profile.totalVisit||0).toLocaleString()}</span>}{profile.showLocation&&profile.location&&<span><MapPin size={12}/> {profile.location}</span>}<span>suffer.info/{profileUsername}</span></div>
   </motion.section>
   <svg style={{display:'none'}}><defs><filter id="name-filter"><feTurbulence type="turbulence" baseFrequency="0.008 1.1" numOctaves="1" seed={seed}/><feDisplacementMap in="SourceGraphic" scale="6" xChannelSelector="R" yChannelSelector="G"/></filter></defs></svg>
   {profile.customCss&&<style>{profile.customCss}</style>}
 </main>;
};
export default ProfilePage;
