import mongoose from 'mongoose';

const siteSettingsSchema = new mongoose.Schema({
  key: { type: String, unique: true, default: 'main' },
  brandName: { type: String, default: 'lost' },
  brandTld: { type: String, default: '.lol' },
  heroBadge: { type: String, default: 'A profile platform built around you' },
  heroTitle: { type: String, default: 'Your entire online identity, in one place.' },
  heroSubtitle: { type: String, default: 'Build a profile that actually feels like yours. Links, socials, music, effects, badges, backgrounds and more — all controlled from one easy dashboard.' },
  primaryButton: { type: String, default: 'Create your profile' },
  secondaryButton: { type: String, default: 'Explore the experience' },
  accentColor: { type: String, default: '#ef4444', match: /^#[0-9a-fA-F]{6}$/ },
  secondaryColor: { type: String, default: '#cbd5e1', match: /^#[0-9a-fA-F]{6}$/ },
  backgroundColor: { type: String, default: '#050506', match: /^#[0-9a-fA-F]{6}$/ },
  panelColor: { type: String, default: '#0d0d0f', match: /^#[0-9a-fA-F]{6}$/ },
  gridOpacity: { type: Number, default: 0.12, min: 0, max: 1 },
  glowOpacity: { type: Number, default: 0.2, min: 0, max: 1 },
  particles: { type: Boolean, default: true },
  grid: { type: Boolean, default: true },
  ghostMode: { type: Boolean, default: true },
  featureSection: { type: Boolean, default: true },
  mediaLayers: { type: [mongoose.Schema.Types.Mixed], default: [] },
  siteAnimations: { type: [mongoose.Schema.Types.Mixed], default: [] },
  announcement: { type: String, default: '' },
  showcaseLabel: { type: String, default: 'Showcase' },
  featuresLabel: { type: String, default: 'Features' },
  signInLabel: { type: String, default: 'Sign in' },
  createLabel: { type: String, default: 'Create page' },
  primaryButtonUrl: { type: String, default: '/register' },
  secondaryButtonUrl: { type: String, default: '#showcase' },
  heroAlignment: { type: String, enum: ['left','center','right'], default: 'center' },
  seoTitle: { type: String, default: 'suffer.info' },
  seoDescription: { type: String, default: 'Create a profile that actually feels like yours.' },
  seoImage: { type: String, default: '' },
  footerText: { type: String, default: 'Your page. Your links. Your rules.' },
  effectsIntensity: { type: Number, default: 1, min: 0, max: 1 },
  navStyle: { type: String, enum: ['glass','solid','minimal','floating'], default: 'glass' },
  heroSize: { type: String, enum: ['compact','standard','large','fullscreen'], default: 'fullscreen' },
  heroWidth: { type: String, enum: ['narrow','standard','wide'], default: 'standard' },
  headlineFont: { type: String, default: 'Inter', maxlength: 80 },
  headlineWeight: { type: Number, default: 600, min: 400, max: 900 },
  headlineSize: { type: Number, default: 8, min: 3, max: 12 },
  bodySize: { type: Number, default: 1, min: .8, max: 1.4 },
  pageRadius: { type: Number, default: 22, min: 0, max: 48 },
  sectionSpacing: { type: Number, default: 28, min: 12, max: 64 },
  noise: { type: Boolean, default: false },
  vignette: { type: Boolean, default: true },
  scanlines: { type: Boolean, default: false },
  animatedGradient: { type: Boolean, default: true },
  mouseGlow: { type: Boolean, default: true },
  hoverLift: { type: Boolean, default: true },
  buttonStyle: { type: String, enum: ['solid','glass','outline','pill'], default: 'solid' },
  buttonRadius: { type: Number, default: 16, min: 0, max: 40 },
  showTrustBar: { type: Boolean, default: true },
  trustText: { type: String, default: 'Free to start · No design skills needed · Your profile, your rules.' },
  showcaseTitle: { type: String, default: 'Make it yours' },
  showcaseDescription: { type: String, default: 'One editor for your profile, links, music, badges, effects and media.' },
  featuresTitle: { type: String, default: 'Everything important is one tap away.' },
  featuresDescription: { type: String, default: 'Powerful controls without making you learn code.' },
  featureCards: { type: [mongoose.Schema.Types.Mixed], default: [] },
  customCss: { type: String, default: '', maxlength: 12000 },
  updatedAt: { type: Date, default: Date.now },
});

export const SiteSettings = mongoose.model('SiteSettings', siteSettingsSchema);
