import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {apiService,AUTH} from '../../../services/api';
import {UserRole} from '../../../types';

type AdminUser={
 id:number;username:string;name?:string;email:string;role:UserRole;premium:boolean;badges:string[];
 totalVisit?:number;verified?:boolean;accentColor?:string;textColor?:string;backgroundColor?:string;
 fontFamily?:string;customFontFamily?:string;profileOpacity?:number;profileBlur?:number;
 usernameEffect?:string;backgroundEffect?:string;cursorEffect?:string;layout?:string;
 customEmojis?:{name:string;value:string}[];
 rootOwner?:boolean;canBan?:boolean;canDemote?:boolean;canManageRoles?:boolean;canManagePremium?:boolean;canManageBadges?:boolean;canCustomizeUsers?:boolean;
 banned?:boolean;banReason?:string;
};

const Field=({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string})=>
<label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span>
<input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-white/10 bg-black/30 px-3 text-sm outline-none focus:border-red-500/50"/></label>;

const Toggle=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>;

const Select=({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]})=>
<label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{label}</span>
<select value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-white/10 bg-[#151315] px-3 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select></label>;

export const AdminPanel:React.FC=()=>{
 const [users,setUsers]=useState<AdminUser[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 const [query,setQuery]=useState(''); const [selected,setSelected]=useState<number|null>(null);
 const [badge,setBadge]=useState(''); const [emojiName,setEmojiName]=useState(''); const [emojiValue,setEmojiValue]=useState('');
 const [saving,setSaving]=useState(false); const [badgeDefs,setBadgeDefs]=useState<any[]>([]); const [me,setMe]=useState<any>(null); const [banReason,setBanReason]=useState(''); const [newBadge,setNewBadge]=useState({name:'',image:'',fontFamily:'Inter',textColor:'#f4f0ef',accentColor:'#ef3340',animation:'glow',description:'',selfClaimable:false,requiredPremium:false,requiredRole:'member',maxHolders:0});
 const load=async()=>{try{setUsers(await apiService.getAdminUsers() as AdminUser[])}catch(e){setError(e instanceof Error?e.message:'Unable to load admin panel')}finally{setLoading(false)}};
 useEffect(()=>{load(); apiService.getAdminBadgeDefinitions().then(setBadgeDefs).catch(()=>setBadgeDefs([])); fetch(AUTH,{headers:{Authorization:`Bearer ${localStorage.getItem('token')??''}`}}).then(r=>r.ok?r.json():null).then(setMe).catch(()=>{});},[]);
 const target=users.find(u=>u.id===selected)||null; const isRootOwner=!!me?.rootOwner;
 const update=async(id:number,body:{role?:UserRole;premium?:boolean})=>{setError('');try{await apiService.updateAdminUser(id,body);await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}};
 const customize=async(body:Record<string,unknown>)=>{if(!target)return;setSaving(true);setError('');try{await apiService.updateAdminCustomization(target.id,body);await load()}catch(e){setError(e instanceof Error?e.message:'Customization update failed')}finally{setSaving(false)}};
 const addBadge=async()=>{if(!target||!badge.trim())return;try{await apiService.addAdminBadge(target.id,badge.trim());setBadge('');await load()}catch(e){setError(e instanceof Error?e.message:'Badge update failed')}};
 const saveBadgeDefinition=async()=>{if(!newBadge.name.trim())return;setSaving(true);setError('');try{const saved=await apiService.saveAdminBadgeDefinition(newBadge);setBadgeDefs(prev=>[...prev.filter(x=>x.name!==saved.name),saved]);setNewBadge({name:'',image:'',fontFamily:'Inter',textColor:'#f4f0ef',accentColor:'#ef3340',animation:'glow',description:'',selfClaimable:false,requiredPremium:false,requiredRole:'member',maxHolders:0});}catch(e){setError(e instanceof Error?e.message:'Badge definition save failed')}finally{setSaving(false)}};
 const deleteBadgeDefinition=async(name:string)=>{try{await apiService.deleteAdminBadgeDefinition(name);setBadgeDefs(prev=>prev.filter(x=>x.name!==name));}catch(e){setError(e instanceof Error?e.message:'Badge definition delete failed')}};
 const readBadgeImage=(file:File)=>{const reader=new FileReader();reader.onload=()=>setNewBadge(v=>({...v,image:String(reader.result||'')}));reader.readAsDataURL(file)};
 const setPermissions=async(body:Record<string,boolean>)=>{if(!target)return;setSaving(true);setError('');try{await apiService.updateAdminPermissions(target.id,body);await load()}catch(e){setError(e instanceof Error?e.message:'Permission update failed')}finally{setSaving(false)}};
 const banUser=async()=>{if(!target)return;setSaving(true);setError('');try{await apiService.banAdminUser(target.id,banReason);setBanReason('');await load()}catch(e){setError(e instanceof Error?e.message:'Ban failed')}finally{setSaving(false)}};
 const unbanUser=async()=>{if(!target)return;setSaving(true);setError('');try{await apiService.unbanAdminUser(target.id);await load()}catch(e){setError(e instanceof Error?e.message:'Unban failed')}finally{setSaving(false)}};
 const removeBadge=async(b:string)=>{if(!target)return;try{await apiService.removeAdminBadge(target.id,b);await load()}catch(e){setError(e instanceof Error?e.message:'Badge removal failed')}};
 const addEmoji=async()=>{if(!target||!emojiName.trim()||!emojiValue.trim())return;const next=[...(target.customEmojis||[]),{name:emojiName.trim(),value:emojiValue.trim()}];await customize({customEmojis:next});setEmojiName('');setEmojiValue('')};
 const filtered=users.filter(u=>`${u.username} ${u.email} ${u.name||''}`.toLowerCase().includes(query.toLowerCase()));
 const color=(v?:string)=>v||'#ef3340';
 return <div className="min-h-screen bg-[#070707] text-white">
  <header className="sticky top-0 z-30 border-b border-white/[.08] bg-[#0b0b0c]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
   <div><Link to="/dashboard" className="text-xl font-black">lost<span className="text-red-500">.lol</span></Link><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Admin control center</div></div>
   <Link to="/dashboard" className="rounded-xl border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Dashboard</Link>
  </div></header>
  <main className="mx-auto max-w-7xl px-5 py-7">
   <div className="mb-6 grid gap-3 sm:grid-cols-4">
    {[['Accounts',users.length],['Premium',users.filter(u=>u.premium).length],['Team',users.filter(u=>u.role!=='member').length],['Verified',users.filter(u=>u.verified).length]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-white/[.07] bg-[#0d0d0f] p-5"><p className="text-xs text-zinc-500">{k}</p><p className="mt-2 text-2xl font-bold">{v}</p></div>)}
   </div>
   {error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
   <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_420px]">
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#0c0c0e]">
     <div className="border-b border-white/[.07] p-4"><Field label="Search accounts" value={query} onChange={setQuery} placeholder="username, email, or display name"/></div>
     {loading?<div className="p-6 text-zinc-500">Loading users...</div>:<div className="divide-y divide-white/[.06]">{filtered.map(u=><button key={u.id} onClick={()=>setSelected(u.id)} className={`block w-full p-4 text-left transition-colors hover:bg-white/[.03] ${selected===u.id?'bg-red-500/[.06]':''}`}>
       <div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate font-semibold">{u.username} {u.verified&&<span className="text-red-400">✓</span>}</div><div className="truncate text-xs text-zinc-500">{u.email}</div></div><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-zinc-400">{u.role}</span></div>
       <div className="mt-3 flex flex-wrap gap-2"><span className="text-[10px] text-zinc-600">{u.totalVisit||0} views</span>{u.premium&&<span className="text-[10px] text-amber-300">premium</span>}{(u.badges||[]).map(b=><span key={b} className="rounded-full bg-red-500/10 px-2 py-1 text-[10px] text-red-300">{b}</span>)}</div>
     </button>)}</div>}
    </section>
    <section className="space-y-4">
     {!target?<div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-6 text-sm text-zinc-500">Select an account to manage roles, premium access, verification, colors, fonts, effects, badges, and custom emojis.</div>:
     <>
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><h2 className="font-semibold">{target.username}{target.rootOwner&&<span className="ml-2 rounded-full bg-red-500/10 px-2 py-1 text-[9px] uppercase tracking-wider text-red-300">Primary owner</span>}</h2><p className="mt-1 text-xs text-zinc-500">{target.email}</p>
       <div className="mt-5 grid gap-3 sm:grid-cols-2">
        <Select label="Role" value={target.role} onChange={v=>update(target.id,{role:v as UserRole})} options={['member','staff','co-owner','owner']}/>
        <div><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Premium</span><button onClick={()=>update(target.id,{premium:!target.premium})} className={`h-10 w-full rounded-xl ${target.premium?'bg-amber-500/20 text-amber-200':'bg-white/10 text-zinc-400'}`}>{target.premium?'Enabled':'Disabled'}</button></div>
       </div>
       <label className="mt-3 flex items-center justify-between rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm"><span>Verified badge</span><input type="checkbox" checked={!!target.verified} onChange={e=>customize({verified:e.target.checked})}/></label>
       <div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Moderation</h3><p className="mt-1 text-xs text-zinc-500">{target.banned?'This account is currently banned.':'Ban or unban this account.'}</p></div><span className={target.banned?'text-red-300':'text-emerald-300'}>{target.banned?'BANNED':'ACTIVE'}</span></div>
       {target.banned?<button disabled={saving||target.rootOwner} onClick={unbanUser} className="mt-3 w-full rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-2.5 text-sm font-semibold text-emerald-300 disabled:opacity-40">Unban user</button>:<><Field label="Ban reason (optional)" value={banReason} onChange={setBanReason} placeholder="Reason shown to the user"/><button disabled={saving||target.rootOwner||(!!me&&!isRootOwner&&!me?.canBan)} onClick={banUser} className="mt-3 w-full rounded-xl bg-red-500/15 px-4 py-2.5 text-sm font-semibold text-red-300 disabled:opacity-40">Ban user</button></>}</div>
      </div>
      {isRootOwner&&!target.rootOwner&&<div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Delegated permissions</h3><p className="mt-1 text-xs text-zinc-500">Only you can grant or revoke these permissions.</p></div><span className="text-[10px] uppercase tracking-wider text-red-300">Owner only</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{([['canDemote','Demote users'],['canBan','Ban / unban users'],['canManageRoles','Manage promotions'],['canManagePremium','Manage Premium'],['canManageBadges','Manage badges'],['canCustomizeUsers','Customize users']] as [keyof AdminUser,string][]).map(([key,label])=><label key={String(key)} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-sm"><span>{label}</span><input type="checkbox" checked={!!target[key]} onChange={e=>setPermissions({[key]:e.target.checked})}/></label>)}</div></div>}
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><h3 className="font-semibold">Colors & fonts</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">
       <Field label="Accent" value={color(target.accentColor)} onChange={v=>customize({accentColor:v})}/><Field label="Text" value={color(target.textColor)} onChange={v=>customize({textColor:v})}/><Field label="Background" value={color(target.backgroundColor)} onChange={v=>customize({backgroundColor:v})}/><Field label="Font family" value={target.fontFamily||'Inter'} onChange={v=>customize({fontFamily:v})}/><Field label="Custom font family" value={target.customFontFamily||''} onChange={v=>customize({customFontFamily:v})}/>
       </div></div>
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><h3 className="font-semibold">Effects & layout</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">
       <Select label="Username effect" value={target.usernameEffect||'none'} onChange={v=>customize({usernameEffect:v})} options={['none','glow','pulse','float','shake','bounce','tilt','zoom','blur','flash','swing','jelly','heartbeat','neon','rainbow']}/>
       <Select label="Background effect" value={target.backgroundEffect||'none'} onChange={v=>customize({backgroundEffect:v})} options={['none','pulse','aurora','scanlines','vignette','grid','spotlight','breathe','flicker','drift','orbit','waves','noise','halo','radar']}/>
       <Select label="Cursor effect" value={target.cursorEffect||'none'} onChange={v=>customize({cursorEffect:v})} options={['none','glow','red']}/>
       <Select label="Layout" value={target.layout||'default'} onChange={v=>customize({layout:v})} options={['default','compact','wide','card']}/>
       <Field label="Opacity (0.4–1)" value={String(target.profileOpacity??1)} onChange={v=>customize({profileOpacity:Number(v)})}/>
       <Field label="Blur (0–40)" value={String(target.profileBlur??0)} onChange={v=>customize({profileBlur:Number(v)})}/>
      </div><div className="mt-4 rounded-2xl border border-red-500/15 bg-black/30 p-5 overflow-hidden"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-zinc-600">Live effects preview</div><div className="relative mt-4 flex min-h-32 items-center justify-center overflow-hidden rounded-2xl border border-white/10 bg-[#080808]"><div className="absolute inset-0 opacity-60" style={{background:target.backgroundEffect==='radar'?'radial-gradient(circle,transparent 0,transparent 22%,rgba(239,51,64,.2) 23%,transparent 24%,transparent 48%,rgba(239,51,64,.15) 49%,transparent 50%)':target.backgroundEffect==='grid'?'linear-gradient(rgba(239,51,64,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(239,51,64,.12) 1px,transparent 1px)':'radial-gradient(circle at 50% 50%,rgba(239,51,64,.2),transparent 65%)'}} /><div className={target.usernameEffect==='shake'?'animate-[pulse_.35s_ease-in-out_infinite]':target.usernameEffect==='float'?'animate-[bounce_2s_ease-in-out_infinite]':target.usernameEffect==='pulse'?'animate-pulse':''} style={{color:target.accentColor||'#ef3340',textShadow:['glow','neon'].includes(target.usernameEffect||'')?'0 0 22px currentColor':'none'}}><span className="text-2xl font-black">{target.username}</span></div>{target.cursorEffect==='red'&&<span className="absolute right-8 top-8 h-3 w-3 rounded-full bg-[#ef3340] shadow-[0_0_18px_#ef3340]" />}</div><p className="mt-2 text-[11px] text-zinc-600">Changes save immediately and this preview mirrors the profile effect settings.</p></div></div>
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Badge studio</h3><p className="mt-1 text-xs text-zinc-500">Create reusable badges with their own image, typography, colors and animation.</p></div><span className="rounded-full bg-red-500/10 px-2 py-1 text-[10px] text-red-300">{badgeDefs.length} definitions</span></div>
       <div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Badge name" value={newBadge.name} onChange={v=>setNewBadge(s=>({...s,name:v}))}/><Field label="Font family" value={newBadge.fontFamily} onChange={v=>setNewBadge(s=>({...s,fontFamily:v}))}/><Field label="Description" value={newBadge.description} onChange={v=>setNewBadge(s=>({...s,description:v}))}/><Select label="Required role" value={newBadge.requiredRole} onChange={v=>setNewBadge(s=>({...s,requiredRole:v}))} options={['member','staff','co-owner','owner']}/><Field label="Max holders (0 = unlimited)" value={String(newBadge.maxHolders)} onChange={v=>setNewBadge(s=>({...s,maxHolders:Number(v)||0}))}/><Select label="Animation" value={newBadge.animation} onChange={v=>setNewBadge(s=>({...s,animation:v}))} options={['none','pulse','float','spin','bounce','glow']}/><Field label="Text color" value={newBadge.textColor} onChange={v=>setNewBadge(s=>({...s,textColor:v}))}/><Field label="Accent color" value={newBadge.accentColor} onChange={v=>setNewBadge(s=>({...s,accentColor:v}))}/><Toggle label="Allow users to self-claim" value={!!newBadge.selfClaimable} onChange={v=>setNewBadge(s=>({...s,selfClaimable:v}))}/><Toggle label="Require Premium" value={!!newBadge.requiredPremium} onChange={v=>setNewBadge(s=>({...s,requiredPremium:v}))}/></div>
       <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Image URL (optional)" value={newBadge.image.startsWith('data:')?'':newBadge.image} onChange={v=>setNewBadge(s=>({...s,image:v}))}/><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Badge image</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/svg+xml" onChange={e=>{const f=e.target.files?.[0];if(f)readBadgeImage(f)}} className="h-10 w-full rounded-xl border border-white/10 bg-black/30 px-2 py-2 text-xs text-zinc-400"/></label></div>
       <div className="mt-4 flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4" style={{color:newBadge.textColor,fontFamily:newBadge.fontFamily}}><div className="grid h-11 w-11 place-items-center overflow-hidden rounded-xl bg-black/30">{newBadge.image?<img src={newBadge.image} alt="" className="h-full w-full object-contain"/>:<span className="text-lg font-black">B</span>}</div><div><div className="font-bold">{newBadge.name||'Badge preview'}</div><div className="text-[10px] opacity-60">Live badge preview</div></div></div>
       <button disabled={saving||!newBadge.name.trim()} onClick={saveBadgeDefinition} className="mt-4 rounded-xl bg-red-500 px-4 py-2 text-sm font-semibold disabled:opacity-40">{saving?'Saving…':'Create / update badge'}</button>
       <div className="mt-4 space-y-2">{badgeDefs.map(b=><div key={b.name} className="flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><div className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-lg bg-black/30">{b.image?<img src={b.image} alt="" className="h-full w-full object-contain"/>:<span className="text-xs font-bold">B</span>}</div><div className="min-w-0 flex-1" style={{fontFamily:b.fontFamily,color:b.textColor}}><div className="truncate text-sm font-bold">{b.name}</div><div className="text-[10px] opacity-60">{b.animation} · {b.fontFamily}</div></div><button onClick={()=>deleteBadgeDefinition(b.name)} className="text-xs text-red-400">Delete</button></div>)}</div>
      </div>
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><h3 className="font-semibold">Badges</h3><div className="mt-3 flex flex-wrap gap-2">{(target.badges||[]).map(b=><button key={b} onClick={()=>removeBadge(b)} className="rounded-full bg-red-500/10 px-3 py-1.5 text-xs text-red-300">{b} ×</button>)}</div><div className="mt-3 flex gap-2"><input value={badge} onChange={e=>setBadge(e.target.value)} placeholder="Badge name" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"/><button onClick={addBadge} className="rounded-xl bg-red-500 px-3 py-2 text-sm font-semibold text-white">Give</button></div></div>
      <div className="rounded-2xl border border-white/[.08] bg-[#0c0c0e] p-5"><h3 className="font-semibold">Custom emojis</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><Field label="Name" value={emojiName} onChange={setEmojiName}/><Field label="Value / emoji" value={emojiValue} onChange={setEmojiValue}/></div><button disabled={saving} onClick={addEmoji} className="mt-3 rounded-xl bg-red-500 px-4 py-2 text-sm font-semibold disabled:opacity-50">Add emoji</button><div className="mt-3 space-y-2">{(target.customEmojis||[]).map((e,i)=><div key={`${e.name}-${i}`} className="flex items-center justify-between rounded-xl bg-black/20 px-3 py-2 text-sm"><span>:{e.name}: <span className="text-zinc-500">{e.value}</span></span><button onClick={()=>customize({customEmojis:(target.customEmojis||[]).filter((_,j)=>j!==i)})} className="text-xs text-red-400">Remove</button></div>)}</div></div>
     </>}
    </section>
   </div>
  </main>
 </div>;
};