import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {apiService} from '../../../services/api';
import {UserRole} from '../../../types';

type AdminUser={id:number;username:string;name?:string;email:string;role:UserRole;premium:boolean;badges:string[];totalVisit?:number};
export const AdminPanel:React.FC=()=>{const [users,setUsers]=useState<AdminUser[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true); const [badge,setBadge]=useState('');
 const load=async()=>{try{setUsers(await apiService.getAdminUsers() as AdminUser[])}catch(e){setError(e instanceof Error?e.message:'Unable to load admin panel')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const addBadge=async(id:number)=>{if(!badge.trim())return;try{await apiService.addAdminBadge(id,badge.trim());setBadge('');await load()}catch(e){setError(e instanceof Error?e.message:'Badge update failed')}};
 const update=async(id:number,body:{role?:UserRole;premium?:boolean})=>{try{await apiService.updateAdminUser(id,body);await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}};
 return <div className="min-h-screen bg-[#090909] text-white"><header className="border-b border-white/[.08] bg-[#0e0d0f]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><div><Link to="/dashboard" className="text-xl font-bold">lost<span className="text-orange-500">.lol</span></Link><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Admin panel</div></div><Link to="/dashboard" className="rounded-xl bg-white/10 px-4 py-2 text-sm">Dashboard</Link></div></header><main className="mx-auto max-w-6xl px-5 py-8"><div className="mb-5 rounded-[26px] border border-red-500/20 bg-red-950/10 p-6"><h1 className="text-3xl font-bold">Team & accounts</h1><p className="mt-2 text-zinc-400">Manage roles, premium access and account badges.</p></div>{error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{loading?<div className="text-zinc-500">Loading users...</div>:<div className="overflow-x-auto rounded-2xl border border-white/[.08]"><table className="w-full text-left text-sm"><thead className="bg-white/[.03] text-zinc-500"><tr><th className="p-4">User</th><th className="p-4">Role</th><th className="p-4">Premium</th><th className="p-4">Views</th><th className="p-4">Badges</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/[.06]"><td className="p-4"><div className="font-semibold">{u.username}</div><div className="text-xs text-zinc-500">{u.email}</div></td><td className="p-4"><select value={u.role} onChange={e=>update(u.id,{role:e.target.value as UserRole})} className="rounded-lg border border-white/10 bg-[#151315] px-3 py-2"><option value="member">Member</option><option value="staff">Staff</option><option value="co-owner">Co-owner</option><option value="owner">Owner</option></select></td><td className="p-4"><button onClick={()=>update(u.id,{premium:!u.premium})} className={`rounded-lg px-3 py-2 ${u.premium?'bg-amber-500/20 text-amber-300':'bg-white/10 text-zinc-400'}`}>{u.premium?'Enabled':'Disabled'}</button></td><td className="p-4 text-zinc-400">{u.totalVisit||0}</td><td className="p-4"><div className="flex flex-wrap gap-1">{u.badges?.map(b=><span key={b} className="rounded-full bg-orange-500/10 px-2 py-1 text-[10px] text-orange-300">{b}</span>)}</div><div className="mt-2 flex gap-2"><input value={badge} onChange={e=>setBadge(e.target.value)} placeholder="Badge name" className="w-28 rounded-lg border border-white/10 bg-[#151315] px-2 py-1.5 text-xs"/><button onClick={()=>addBadge(u.id)} className="rounded-lg bg-orange-500 px-2 py-1.5 text-xs font-semibold text-black">Give</button></div></td></tr>)}</tbody></table></div>}</main></div>};